apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-deployment
  namespace: gestion
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gestion
  template:
    metadata:
      labels:
        app: gestion
    spec:
      containers:
        - name: gestion
          image: harbor.local:8081/staging/gestion:v1.57
          ports:
            - containerPort: 80
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/gestion_db?serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
