apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-deployment
  namespace: gestion
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gestion
  template:
    metadata:
      labels:
        app: gestion
    spec:
      containers:
        - name: gestion
          image: harbor.local:8081/staging/gestion:v1.60
          ports:
            - containerPort: 80
          env:
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: ADMIN_PASSWORD
