apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-deployment
  namespace: gestion
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gestion
  template:
    metadata:
      labels:
        app: gestion
    spec:
      imagePullSecrets:
        - name: harbor-regcred   
      containers:
        - name: gestion
          image: harbor.local:8081/staging/gestion:v1.57
          ports:
            - containerPort: 80
