apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: gestion
type: Opaque
stringData:
  MYSQL_DATABASE: gestion_db
  MYSQL_USER: Charbel
  MYSQL_PASSWORD: Charbel
  MYSQL_ROOT_PASSWORD: rootpass
