apiVersion: v1
kind: Service
metadata:
  name: gestion-service
spec:
  type: NodePort
  selector:
    app: gestion
  ports:
    - port: 80          # Port du service (interne au cluster)
      targetPort: 80   # Port du container
      nodePort: 30080  # Port exposé sur le nœud (entre 30000-32767)
